preserve = true
allow_duplicate = true
xml_path = '/path/to/xml_file'
rtf_path = '/path/to/rtf_file'
img_path = '/path/to/game/img/directory'
fm_version = '2024'

[mapping_override]
AFG = 'MESA'
AIA = 'African'
ALB = 'YugoGreek'
ALG = 'MENA'
AND = 'SpanMed'
ANG = 'African'
ARG = 'SAMed'
ARM = 'EECA'
ARU = 'African'
ASA = 'African'
ATG = 'African'
AUS = 'Central European'
AUT = 'Central European'
AXL = 'Scandinavian'
AZE = 'EECA'
BAH = 'African'
BAN = 'MESA'
BAS = 'SpanMed'
BDI = 'African'
BEL = 'Central European'
BEN = 'African'
BER = 'African'
BFA = 'African'
BHR = 'MESA'
BHU = 'Asian'
BIH = 'YugoGreek'
BLM = 'Caucasian'
BLR = 'EECA'
BLZ = 'South American'
BOE = 'African'
BOL = 'South American'
BOT = 'African'
BRA = 'South American'
BRB = 'African'
BRU = 'Seasian'
BUL = 'EECA'
CAM = 'Seasian'
CAN = 'Caucasian'
CAY = 'African'
CGO = 'African'
CHA = 'African'
CHI = 'South American'
CHN = 'Asian'
CIV = 'African'
CMR = 'African'
COD = 'African'
COK = 'African'
COL = 'South American'
COM = 'African'
CPV = 'African'
CRC = 'South American'
CRO = 'YugoGreek'
CTA = 'African'
CUB = 'South American'
CUW = 'African'
CYP = 'MENA'
CZE = 'EECA'
DEN = 'Scandinavian'
DJI = 'African'
DMA = 'African'
DOM = 'South American'
ECU = 'South American'
EGY = 'MENA'
ENG = 'Caucasian'
EQG = 'African'
ERI = 'African'
ESP = 'SpanMed'
EST = 'EECA'
ESW = 'African'
ETH = 'African'
FIJ = 'African'
FIN = 'Scandinavian'
FRA = 'Central European'
FRO = 'Scandinavian'
FSM = 'African'
GAB = 'African'
GAM = 'African'
GBR = 'Caucasian'
GEO = 'EECA'
GER = 'Central European'
GHA = 'African'
GIB = 'Caucasian'
GLP = 'African'
GNB = 'African'
GRE = 'YugoGreek'
GRL = 'Caucasian'
GRN = 'African'
GUA = 'South American'
GUF = 'African'
GUI = 'African'
GUM = 'African'
GUY = 'African'
HAI = 'African'
HKG = 'Asian'
HON = 'South American'
HUN = 'Central European'
IDN = 'Seasian'
IND = 'MESA'
IRL = 'Caucasian'
IRN = 'MESA'
IRQ = 'MESA'
ISL = 'Scandinavian'
ISR = 'MENA'
ITA = 'Italmed'
JAM = 'African'
JOR = 'MESA'
JPN = 'Asian'
KAZ = 'EECA'
KEN = 'African'
KGZ = 'EECA'
KIR = 'African'
KOR = 'Asian'
KOS = 'YugoGreek'
KSA = 'MESA'
KUW = 'MESA'
KVX = 'YugoGreek'
LAO = 'Seasian'
LBN = 'MENA'
LBR = 'African'
LBY = 'African'
LCA = 'African'
LES = 'African'
LIB = 'MENA'
LIE = 'Central European'
LTU = 'EECA'
LUX = 'Central European'
LVA = 'EECA'
MAC = 'Asian'
MAD = 'African'
MAR = 'MENA'
MAS = 'Seasian'
MAY = 'African'
MDA = 'EECA'
MDV = 'African'
MEX = 'South American'
MGL = 'Asian'
MKD = 'EECA'
MLI = 'African'
MLT = 'Italmed'
MNE = 'YugoGreek'
MNG = 'Asian'
MON = 'Italmed'
MOZ = 'African'
MRI = 'African'
MSR = 'African'
MTN = 'African'
MTQ = 'African'
MWI = 'African'
MYA = 'Seasian'
NAM = 'African'
NCA = 'South American'
NCL = 'African'
NED = 'Central European'
NEP = 'MESA'
NGA = 'African'
NIG = 'African'
NIR = 'Caucasian'
NIU = 'African'
NMI = 'African'
NOR = 'Scandinavian'
NZL = 'Caucasian'
OMA = 'MESA'
PAK = 'MESA'
PAN = 'South American'
PAR = 'South American'
PER = 'South American'
PHI = 'Seasian'
PLE = 'MESA'
PLW = 'African'
PNG = 'African'
POL = 'Central European'
POR = 'SpanMed'
PRK = 'Asian'
PUR = 'South American'
QAT = 'MESA'
REU = 'African'
ROU = 'EECA'
RSA = 'African'
RUS = 'EECA'
RWA = 'African'
SAM = 'African'
SCO = 'Caucasian'
SDN = 'African'
SEN = 'African'
SEY = 'African'
SGP = 'Asian'
SIN = 'Seasian'
SKN = 'African'
SLE = 'African'
SLV = 'South American'
SMA = 'African'
SMN = 'African'
SMR = 'Italmed'
SOL = 'African'
SOM = 'African'
SPM = 'Caucasian'
SRB = 'YugoGreek'
SRI = 'African'
SSD = 'African'
STP = 'African'
SUD = 'MENA'
SUI = 'Central European'
SUR = 'African'
SVK = 'Central European'
SVN = 'YugoGreek'
SWE = 'Scandinavian'
SWZ = 'African'
SYR = 'MESA'
TAH = 'African'
TAN = 'African'
TCA = 'African'
TGA = 'African'
THA = 'Seasian'
TJK = 'EECA'
TKM = 'EECA'
TLS = 'African'
TOG = 'African'
TPE = 'Asian'
TRI = 'African'
TUN = 'MENA'
TUR = 'MENA'
TUV = 'African'
UAE = 'MESA'
UGA = 'African'
UKR = 'EECA'
URU = 'SAMed'
USA = 'Caucasian'
UZB = 'EECA'
VAN = 'African'
VAT = 'Caucasian'
VEN = 'South American'
VGB = 'African'
VIE = 'Seasian'
VIN = 'African'
VIR = 'African'
WAL = 'Caucasian'
WFI = 'African'
YEM = 'MESA'
ZAM = 'African'
ZAN = 'African'
ZIM = 'African'
