package mapper

const (
	African                     Ethnic = "African"
	Asian                       Ethnic = "Asian"
	Caucasian                   Ethnic = "Caucasian"
	CentralEuropean             Ethnic = "Central European"
	EasternEuropeanCentralAsian Ethnic = "EECA"
	ItalianMediterranean        Ethnic = "Italmed"
	MiddleEastNorthAfrican      Ethnic = "MENA"
	MiddleEastSouthAmerican     Ethnic = "MESA"
	SouthAmericanMediterranean  Ethnic = "SAMed"
	Scandinavian                Ethnic = "Scandinavian"
	SouthEastAsian              Ethnic = "Seasian"
	SouthAmerican               Ethnic = "South American"
	SpanishMediterranean        Ethnic = "SpanMed"
	YugoslavGreek               Ethnic = "YugoGreek"
)

var Ethnicities = [...]Ethnic{
	African,
	Asian,
	Caucasian,
	CentralEuropean,
	EasternEuropeanCentralAsian,
	ItalianMediterranean,
	MiddleEastNorthAfrican,
	MiddleEastSouthAmerican,
	SouthAmericanMediterranean,
	Scandinavian,
	SouthEastAsian,
	SouthAmerican,
	SpanishMediterranean,
	YugoslavGreek,
}

var NationEthnicMapping = map[string]Ethnic{
	"AFG": MiddleEastSouthAmerican,
	"AXL": Scandinavian,
	"ALB": YugoslavGreek,
	"ALG": MiddleEastNorthAfrican,
	"ASA": African,
	"AND": SpanishMediterranean,
	"ANG": African,
	"AIA": African,
	"ATG": African,
	"ARG": SouthAmericanMediterranean,
	"ARM": EasternEuropeanCentralAsian,
	"ARU": African,
	"AUS": CentralEuropean,
	"AUT": CentralEuropean,
	"AZE": EasternEuropeanCentralAsian,
	"BAS": SpanishMediterranean,
	"BAH": African,
	"BHR": MiddleEastSouthAmerican,
	"BAN": MiddleEastSouthAmerican,
	"BRB": African,
	"BLR": EasternEuropeanCentralAsian,
	"BEL": CentralEuropean,
	"BLZ": SouthAmerican,
	"BEN": African,
	"BER": African,
	"BHU": Asian,
	"BOL": SouthAmerican,
	"BIH": YugoslavGreek,
	"BOT": African,
	"BRA": SouthAmerican,
	"VGB": African,
	"BRU": SouthEastAsian,
	"BUL": EasternEuropeanCentralAsian,
	"BFA": African,
	"BDI": African,
	"CAM": SouthEastAsian,
	"CMR": African,
	"CAN": Caucasian,
	"CPV": African,
	"CAY": African,
	"CTA": African,
	"CHA": African,
	"CHI": SouthAmerican,
	"CHN": Asian,
	"COL": SouthAmerican,
	"COM": African,
	"COD": African,
	"CGO": African,
	"COK": African,
	"CRC": SouthAmerican,
	"CIV": African,
	"CRO": YugoslavGreek,
	"CUB": SouthAmerican,
	"CUW": African,
	"CYP": MiddleEastNorthAfrican,
	"CZE": EasternEuropeanCentralAsian,
	"DEN": Scandinavian,
	"DJI": African,
	"DMA": African,
	"DOM": SouthAmerican,
	"ECU": SouthAmerican,
	"EGY": MiddleEastNorthAfrican,
	"SLV": SouthAmerican,
	"ENG": Caucasian,
	"EQG": African,
	"ERI": African,
	"EST": EasternEuropeanCentralAsian,
	"SWZ": African,
	"ETH": African,
	"FRO": Scandinavian,
	"FIJ": African,
	"FIN": Scandinavian,
	"FRA": CentralEuropean,
	"TAH": African,
	"GAB": African,
	"GAM": African,
	"GEO": EasternEuropeanCentralAsian,
	"GER": CentralEuropean,
	"GHA": African,
	"GIB": Caucasian,
	"GRE": YugoslavGreek,
	"GRL": Caucasian,
	"GRN": African,
	"GLP": African,
	"GUM": African,
	"GUA": SouthAmerican,
	"GUI": African,
	"GNB": African,
	"GUY": African,
	"HAI": African,
	"HON": SouthAmerican,
	"HKG": Asian,
	"HUN": CentralEuropean,
	"ISL": Scandinavian,
	"IND": MiddleEastSouthAmerican,
	"IDN": SouthEastAsian,
	"IRN": MiddleEastSouthAmerican,
	"IRQ": MiddleEastSouthAmerican,
	"IRL": Caucasian,
	"ISR": MiddleEastNorthAfrican,
	"ITA": ItalianMediterranean,
	"JAM": African,
	"JPN": Asian,
	"JOR": MiddleEastSouthAmerican,
	"KAZ": EasternEuropeanCentralAsian,
	"KEN": African,
	"KIR": African,
	"PRK": Asian,
	"KOR": Asian,
	"KVX": YugoslavGreek,
	"KUW": MiddleEastSouthAmerican,
	"KGZ": EasternEuropeanCentralAsian,
	"LAO": SouthEastAsian,
	"LVA": EasternEuropeanCentralAsian,
	"LBN": MiddleEastNorthAfrican,
	"LES": African,
	"LBR": African,
	"LBY": African,
	"LIE": CentralEuropean,
	"LTU": EasternEuropeanCentralAsian,
	"LUX": CentralEuropean,
	"MAC": Asian,
	"MAD": African,
	"MWI": African,
	"MAS": SouthEastAsian,
	"MDV": African,
	"MLI": African,
	"MLT": ItalianMediterranean,
	"MTQ": African,
	"MTN": African,
	"MRI": African,
	"MEX": SouthAmerican,
	"FSM": African,
	"MDA": EasternEuropeanCentralAsian,
	"MON": ItalianMediterranean,
	"MNG": Asian,
	"MNE": YugoslavGreek,
	"MSR": African,
	"MAR": MiddleEastNorthAfrican,
	"MOZ": African,
	"MYA": SouthEastAsian,
	"NAM": African,
	"NEP": MiddleEastSouthAmerican,
	"NED": CentralEuropean,
	"NCL": African,
	"NZL": Caucasian,
	"NCA": SouthAmerican,
	"NIG": African,
	"NGA": African,
	"NIU": African,
	"NIR": Caucasian,
	"NMI": African,
	"MKD": EasternEuropeanCentralAsian,
	"NOR": Scandinavian,
	"OMA": MiddleEastSouthAmerican,
	"PAK": MiddleEastSouthAmerican,
	"PLW": African,
	"PLE": MiddleEastSouthAmerican,
	"PAN": SouthAmerican,
	"PNG": African,
	"PAR": SouthAmerican,
	"PER": SouthAmerican,
	"PHI": SouthEastAsian,
	"POL": CentralEuropean,
	"POR": SpanishMediterranean,
	"PUR": SouthAmerican,
	"QAT": MiddleEastSouthAmerican,
	"REU": African,
	"ROU": EasternEuropeanCentralAsian,
	"RUS": EasternEuropeanCentralAsian,
	"RWA": African,
	"SKN": African,
	"LCA": African,
	"SMN": African,
	"VIN": African,
	"SAM": African,
	"SMR": ItalianMediterranean,
	"STP": African,
	"KSA": MiddleEastSouthAmerican,
	"SCO": Caucasian,
	"SEN": African,
	"SRB": YugoslavGreek,
	"SEY": African,
	"SLE": African,
	"SIN": SouthEastAsian,
	"SMA": African,
	"SVK": CentralEuropean,
	"SVN": YugoslavGreek,
	"SOL": African,
	"SOM": African,
	"RSA": African,
	"SSD": African,
	"ESP": SpanishMediterranean,
	"SRI": African,
	"SDN": African,
	"SUR": African,
	"SWE": Scandinavian,
	"SUI": CentralEuropean,
	"SYR": MiddleEastSouthAmerican,
	"TPE": Asian,
	"TJK": EasternEuropeanCentralAsian,
	"TAN": African,
	"THA": SouthEastAsian,
	"TLS": African,
	"TOG": African,
	"TGA": African,
	"TRI": African,
	"TUN": MiddleEastNorthAfrican,
	"TUR": MiddleEastNorthAfrican,
	"TKM": EasternEuropeanCentralAsian,
	"TCA": African,
	"TUV": African,
	"UGA": African,
	"UKR": EasternEuropeanCentralAsian,
	"UAE": MiddleEastSouthAmerican,
	"GBR": Caucasian,
	"USA": Caucasian,
	"VIR": African,
	"URU": SouthAmericanMediterranean,
	"UZB": EasternEuropeanCentralAsian,
	"VAN": African,
	"VAT": Caucasian,
	"VEN": SouthAmerican,
	"VIE": SouthEastAsian,
	"WAL": Caucasian,
	"YEM": MiddleEastSouthAmerican,
	"ZAM": African,
	"ZIM": African,
	"ZAN": African,
	"LIB": MiddleEastNorthAfrican,
	"GUF": African,
	"WFI": African,
	"SUD": MiddleEastNorthAfrican,
	"MAY": African,
	"BOE": African,
	"BLM": Caucasian,
	"SPM": Caucasian,
	"MGL": Asian,
	"KOS": YugoslavGreek,
	"ESW": African,
	"SGP": Asian,
}
